version: '3.7'
services:
    traefik:
        image: traefik:2.4
        command:
            --providers.docker=true
            --providers.docker.watch=true
            --providers.docker.swarmmode=true
            --providers.docker.exposedbydefault=false
            --entrypoints.http.address=:80
            --entrypoints.https.address=:443
            --certificatesresolvers.letsencrypt.acme.httpchallenge=true
            --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
            --certificatesresolvers.letsencrypt.acme.email=mail@elisdn.ru
            --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-public-certs:/certs
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.services.traefik.loadbalancer.server.port=80
                - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
                - traefik.http.routers.http-catchall.entrypoints=http
                - traefik.http.routers.http-catchall.middlewares=redirect-to-https
                - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
                - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
            placement:
                constraints: [ node.role == manager ]

networks:
    traefik-public:
        external: true

volumes:
    traefik-public-certs:
